default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  timeout: 5000
  username: jahangeer
  password:
  database: testing_project

development:
  <<: *default

test:
  <<: *default
  database: testing_project-test
